apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-ai
spec:
  selector:
    matchLabels:
      app: chess-ai
      tier: backend
      track: stable
  replicas: 7
  template:
    metadata:
      labels:
        app: chess-ai
        tier: backend
        track: stable
    spec:
      containers:
        - name: chess-ai
          image: "djkormo/chess-ai"
          ports:
            - name: http
              containerPort: 80