apiVersion: v1
kind: Service
metadata:
  name: chess-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: chess-api
  type: LoadBalancer
