apiVersion: v1
kind: Service
metadata:
  name: my-app-re
  labels:
    app: my-app-re
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app-re
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-re
  labels:
    app: my-app-re
spec:
  replicas: 8
  selector:
    matchLabels:
      app: my-app-re
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-app-re
  template:
    metadata:
      labels:
        app: my-app-re
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app-re
        image: djkormo/chess-ai:blue
        resources:
          limits:
            cpu: "0.2"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        ports:
        - name: http
          containerPort: 80
        - name: probe
          containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: probe
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: probe
          periodSeconds: 10
