from jupyter/minimal-notebook
# cloning repos
RUN git clone https://github.com/macwilam/KursPython.git

RUN git  https://github.com/djkormo/PythonForML.git 

RUN git  https://github.com/hzitoun/cognitiveclass-applied-data-science-with-python.git


# copying repo to working dir
RUN cp -R KursPython ~/work

# copying repo to working dir
RUN cp -R PythonForML ~/work

# copying repo to working dir
RUN cp -R cognitiveclass-applied-data-science-with-python ~/work

